language: cpp

compiler:
  - gcc
  - clang

sudo: false

git:
  depth: 1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - libhiredis-dev

script:
  # make distcheck still does not work on travis
  - mkdir build
    && cd build
    && cmake ..
       -DCMAKE_C_FLAGS="-Werror"
       -DCMAKE_CXX_FLAGS="-Werror"
    && make VERBOSE=1
    && (make test || true)
